### ISSUE TITLE
some petz will teleport through the floor or ceiling, until they find an open area

### ISSUE THREAD

**Issue by fluxionary** [runsy/petz#133]
this is particularly evident with spiders and rats, which can spawn below a player, get into a 1 tile gap, jump, and end up inside the player's basement, giving the feeling that the spiders/rats are spawning in the player's protected base. 

elephants tend to descend into the ground instead of the ceiling, they can often be seen in the ground when using noclip, and eventually end up in caves 

kitties will sometimes ascend when you place a node above them. this doesn't seem to be perfectly reliable, but it's happened to me and at least one other player. 

IMO the code that looks for a place for petz to be if they are "in a wall" should check for nearby air nodes all around, not just up or down.

**Comment by runsy** [comment]
I have fixed the algorithm, now it checks for adjacent suitable nodes for stand on.

Regarding to elephants I have to test them more.

**Comment by fluxionary** [comment]
> Regarding to elephants I have to test them more.

i was able to get this to occur regularly, using ethereal, and hanging out in a savanna biome w/ a lot of hills. after AFKing for an hour or so, and flying into the ground, i could find plenty of elephants descending.

**Comment by fluxionary** [comment]
after testing the latest commits to master, the behavior is exactly the same. tarantulas, rats, and kitties teleport up. elephants teleport down. they don't try to find closer nearby air, even if they're mostly in air.

**Comment by runsy** [comment]
> after testing the latest commits to master, the behavior is exactly the same. tarantulas, rats, and kitties teleport up. elephants teleport down. they don't try to find closer nearby air, even if they're mostly in air.

Very rare.

Test this: Put a kitty on the world. Then put a block where a kitty is. The kittie will go to the adyacent node not above.

**Comment by fluxionary** [comment]
get a kitty into a 1 node high gap:
![screenshot_20221225_121546](https://user-images.githubusercontent.com/25628292/209480969-db61d352-cdb9-4930-92db-61463d7caa38.png)

place a node on the kitty:
![screenshot_20221225_121601](https://user-images.githubusercontent.com/25628292/209480976-8d73761e-19af-42a7-ad35-b783c690c72f.png)

the kitty will teleport up until it finds a place to stand, instead of being displaced sideways:
![screenshot_20221225_121606](https://user-images.githubusercontent.com/25628292/209480991-8db06ea5-282c-43e8-81e1-ca2be61c9703.png)

**Comment by runsy** [comment]
> get a kitty into a 1 node high gap: ![screenshot_20221225_121546](https://user-images.githubusercontent.com/25628292/209480969-db61d352-cdb9-4930-92db-61463d7caa38.png)
> 
> place a node on the kitty: ![screenshot_20221225_121601](https://user-images.githubusercontent.com/25628292/209480976-8d73761e-19af-42a7-ad35-b783c690c72f.png)
> 
> the kitty will teleport up until it finds a place to stand, instead of being displaced sideways: ![screenshot_20221225_121606](https://user-images.githubusercontent.com/25628292/209480991-8db06ea5-282c-43e8-81e1-ca2be61c9703.png)

I see. It is not the same spawn than the suffocation check.

I fixed in the last version.

**Comment by fluxionary** [comment]
i see there is now a message "you cannot put the Petz there", which seems to prevent placing petz while indoors? that doesn't seem right. 

also, if i place them in a totally open area, they telelport far up into the sky and then fall to their death :(

**Comment by runsy** [comment]
> i see there is now a message "you cannot put the Petz there", which seems to prevent placing petz while indoors? that doesn't seem right.
> 
> also, if i place them in a totally open area, they telelport far up into the sky and then fall to their death :(

Fixed.

**Comment by fluxionary** [comment]
@runsy i'm about to go to sleep, i will check this in my tomorrow. thank you for your work :)

**Comment by fluxionary** [comment]
petz no longer teleport into the sky and can be placed when the roof is at least 2 nodes up, but the original issue remains. a petz in a narrow gap will teleport up an arbitrary amount instead of to the nearest open area when a node is placed on top of them.

**Comment by fluxionary** [comment]
it also still happens if e.g. a spider or rat crawls inside a 1-block-tall gap and jumps.

also elephants still teleport down instead of up for whatever reason.

**Comment by runsy** [comment]
Try the new implementation I did for rats and spiders.

**Comment by fluxionary** [comment]
rats and spiders seem to be behaving finally, yay :)

kitties still teleport up and not to adjacent open space.

**Comment by yl-whosit** [comment]
Many petz have their center/origin outside of their collision box. This means that when they get close enough to the bottom of the block, they are considered inside of it and get teleported up (even if their collision box is still outside of it).

Take a bunny collision box for example:
```
local p1 = {x= -0.25, y = -0.5, z = -0.125}
local p2 = {x= 0.25, y = -0.0625, z = 0.1875}
```

Here's how it looks (the bubble/dot is the point that `ent:get_pos()` returns):
![Screenshot 2024-01-25 053304](https://github.com/runsy/petz/assets/138972279/4e4b5a23-86cd-4acc-8c3c-2de72502af8a)

If you put them in a box with quarter slab floor, they will teleport up as soon as they jump:
![Screenshot 2024-01-25 053700](https://github.com/runsy/petz/assets/138972279/1e9f7d26-38a1-4c43-9218-530c71846262)

If the collision box is moved 0.25 units up, like this:
```
local p1 = {x= -0.25, y = -0.25, z = -0.125}
local p2 = {x= 0.25, y = 0.1875, z = 0.1875}
```
And 3d model also raised by 0.25...

Then you have bunnies happily sitting and jumping even in a much tighter space (notice where the center point is now):
![Screenshot 2024-01-25 055025](https://github.com/runsy/petz/assets/138972279/dc73736e-2ec9-4895-9f4a-894788e74140)
